"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False)

ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(',')

FRONTEND_DOMAIN = config('FRONTEND_DOMAIN', default='localhost:3000')
FRONTEND_PROTOCOL = config('FRONTEND_PROTOCOL', default='http')
FRONTEND_SITE_NAME = config('FRONTEND_SITE_NAME', default='RentFlow')
API_BASE_URL = config('API_BASE_URL', default='http://127.0.0.1:8000')
INVITATION_ACCEPT_URL = config(
    'INVITATION_ACCEPT_URL',
    default=f'{FRONTEND_PROTOCOL}://{FRONTEND_DOMAIN}/accept-invite?token={{token}}',
)

EMAIL_BACKEND = config(
    'EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', cast=int, default=587)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool, default=True)
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'no-reply@rentflow.local'
)

REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379')

SMS_PROVIDER = config('SMS_PROVIDER', default='africastalking')
SMS_SIMULATE = config('SMS_SIMULATE', cast=bool, default=True)
AFRICASTALKING_USERNAME = config('AFRICASTALKING_USERNAME', default='')
AFRICASTALKING_API_KEY = config('AFRICASTALKING_API_KEY', default='')
AFRICASTALKING_SENDER_ID = config('AFRICASTALKING_SENDER_ID', default='')
AFRICASTALKING_WHATSAPP_NUMBER = config('AFRICASTALKING_WHATSAPP_NUMBER', default='')

WHATSAPP_PROVIDER = config('WHATSAPP_PROVIDER', default='africastalking')
WHATSAPP_SIMULATE = config('WHATSAPP_SIMULATE', cast=bool, default=True)
WHATSAPP_USE_TEMPLATE = config('WHATSAPP_USE_TEMPLATE', cast=bool, default=False)
WHATSAPP_TEMPLATE_NAME = config('WHATSAPP_TEMPLATE_NAME', default='')
WHATSAPP_TEMPLATE_LANGUAGE = config('WHATSAPP_TEMPLATE_LANGUAGE', default='en')
WHATSAPP_TEMPLATE_CATEGORY = config('WHATSAPP_TEMPLATE_CATEGORY', default='UTILITY')
WHATSAPP_VERIFY_TTL_MINUTES = config('WHATSAPP_VERIFY_TTL_MINUTES', cast=int, default=10)

NOTIFICATION_CHANNELS = [
    item.strip()
    for item in config('NOTIFICATION_CHANNELS', default='email,sms,whatsapp').split(',')
    if item.strip()
]
RENT_REMINDER_DAYS = [
    item.strip()
    for item in config('RENT_REMINDER_DAYS', default='-3,0,3,7,15').split(',')
    if item.strip()
]

PAYMENT_AUTO_SEND_RECEIPT = config('PAYMENT_AUTO_SEND_RECEIPT', cast=bool, default=False)

# Ops alerts
OPS_ALERTS_ENABLED = config('OPS_ALERTS_ENABLED', cast=bool, default=False)
OPS_ALERTS_EMAILS = [
    item.strip()
    for item in config('OPS_ALERTS_EMAILS', default='').split(',')
    if item.strip()
]

# CinetPay (Billing)
CINETPAY_ENABLED = config('CINETPAY_ENABLED', cast=bool, default=False)
CINETPAY_API_KEY = config('CINETPAY_API_KEY', default='')
CINETPAY_SITE_ID = config('CINETPAY_SITE_ID', default='')
CINETPAY_SECRET_KEY = config('CINETPAY_SECRET_KEY', default='')
CINETPAY_BASE_URL = config(
    'CINETPAY_BASE_URL',
    default='https://api-checkout.cinetpay.com/v2/payment',
)
CINETPAY_CHECK_URL = config(
    'CINETPAY_CHECK_URL',
    default='https://api-checkout.cinetpay.com/v2/payment/check',
)
CINETPAY_NOTIFY_URL = config(
    'CINETPAY_NOTIFY_URL',
    default=f'{API_BASE_URL}/api/v1/billing/cinetpay/webhook/',
)
CINETPAY_RETURN_URL = config(
    'CINETPAY_RETURN_URL',
    default=f'{FRONTEND_PROTOCOL}://{FRONTEND_DOMAIN}/billing/return',
)
CINETPAY_CHANNELS = config('CINETPAY_CHANNELS', default='ALL')
CINETPAY_LANG = config('CINETPAY_LANG', default='FR')
CINETPAY_CUSTOMER_COUNTRY = config('CINETPAY_CUSTOMER_COUNTRY', default='BF')
CINETPAY_CUSTOMER_CITY = config('CINETPAY_CUSTOMER_CITY', default='Ouagadougou')
CINETPAY_CUSTOMER_ADDRESS = config('CINETPAY_CUSTOMER_ADDRESS', default='N/A')
CINETPAY_CUSTOMER_ZIP = config('CINETPAY_CUSTOMER_ZIP', default='00000')
CINETPAY_CUSTOMER_STATE = config('CINETPAY_CUSTOMER_STATE', default='BF')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'djoser',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'axes',
    'django_celery_beat',
    
    'apps.accounts.apps.AccountsConfig',
    'apps.agencies.apps.AgenciesConfig',
    'apps.leases.apps.LeasesConfig',
    'apps.payments.apps.PaymentsConfig',
    'apps.properties.apps.PropertiesConfig',
    'apps.notifications.apps.NotificationsConfig',
    'apps.billing.apps.BillingConfig',
    'apps.ops.apps.OpsConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000'
).split(',')

CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', cast=bool, default=True)

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'apps.accounts.backends.PhoneOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

DJOSER = {
    'LOGIN_FIELD': 'phone_number',
    'SEND_ACTIVATION_EMAIL': True,
    'SEND_CONFIRMATION_EMAIL': True,
    'USER_CREATE_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': False,
    'ACTIVATION_URL': (
        f'{FRONTEND_PROTOCOL}://{FRONTEND_DOMAIN}/activate?uid={{uid}}&token={{token}}'
    ),
    'PASSWORD_RESET_CONFIRM_URL': (
        f'{FRONTEND_PROTOCOL}://{FRONTEND_DOMAIN}/reset-password?uid={{uid}}&token={{token}}'
    ),
    'EMAIL_FRONTEND_DOMAIN': FRONTEND_DOMAIN,
    'EMAIL_FRONTEND_PROTOCOL': FRONTEND_PROTOCOL,
    'EMAIL_FRONTEND_SITE_NAME': FRONTEND_SITE_NAME,
    'SERIALIZERS': {
        'user_create': 'apps.accounts.serializers.UserCreateSerializer',
        'user_create_password_retype': 'apps.accounts.serializers.UserCreatePasswordRetypeSerializer',
        'user': 'apps.accounts.serializers.UserSerializer',
        'current_user': 'apps.accounts.serializers.UserSerializer',
    },
}

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=30)
AXES_RESET_ON_SUCCESS = True
AXES_LOCK_OUT_AT_FAILURE = True
AXES_USERNAME_FORM_FIELD = "login"
AXES_ENABLE_ADMIN = True


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "login": "10/minute",
        "password_reset": "5/hour",
        "activation": "10/hour",
    },
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1"],
    "VERSION_PARAM": "version",
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_OBTAIN_SERIALIZER': 'apps.accounts.serializers.PhoneOrEmailTokenObtainPairSerializer',
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST': config('DATABASE_HOST'),
        'PORT': config('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'GMT'

USE_I18N = True

USE_TZ = True

# Celery
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=REDIS_URL)
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=REDIS_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
