# Generated by Django 6.0.3 on 2026-03-17 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_tenant_lease_tenant_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_email', models.BooleanField(default=True)),
                ('allow_sms', models.BooleanField(default=True)),
                ('allow_whatsapp', models.BooleanField(default=True)),
                ('remind_days', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='leases.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Notification Preference',
                'verbose_name_plural': 'Tenant Notification Preferences',
            },
        ),
    ]
