# Generated by Django 6.0.3 on 2026-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_tenantnotificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantnotificationpreference',
            name='whatsapp_verification_code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='tenantnotificationpreference',
            name='whatsapp_verification_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantnotificationpreference',
            name='whatsapp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantnotificationpreference',
            name='whatsapp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
