# Generated by Django 6.0.3 on 2026-03-17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=255, unique=True)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(choices=[("running", "Running"), ("success", "Success"), ("failure", "Failure")], default="success", max_length=20)),
                ("last_error", models.TextField(blank=True)),
                ("run_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task run",
                "verbose_name_plural": "Task runs",
                "ordering": ["task_name"],
            },
        ),
    ]
