# Generated by Django 6.0.3 on 2026-03-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='last_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
