# Generated by Django 6.0.3 on 2026-03-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyinvoice',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='agencyinvoice',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agencyinvoice',
            name='provider_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyinvoice',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agencyinvoice',
            name='provider_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
