# Generated by Django 6.0.3 on 2026-03-15 19:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('room', 'Room'), ('land', 'Land'), ('office', 'Office')], default='house', max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
