# Generated by ChatGPT on 2026-03-15

from django.db import migrations, models
from django.db.models import Q


def fill_missing_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(Q(email__isnull=True) | Q(email="")):
        user.email = f"{user.phone_number}@example.local"
        user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_id"),
    ]

    operations = [
        migrations.RunPython(fill_missing_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(unique=True),
        ),
    ]
